# -*- coding: utf-8 -*-
"""project beautifulsoup stock market project 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-Wei-UM3PSIz37njuUkScLEifycBKzF
"""

from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.sharesansar.com/live-trading', 'html.parser')
soup = requests.get(url)
soup

soup = BeautifulSoup(soup.text,'lxml')
soup.table

#all_data =[]
#heading = soup.find_all('th')

#for data in heading:
  #i = data.text.strip()
  #all_data.append(i)
alldata = []
column = soup.find_all('tr')
for rows in column:
  row_data = rows.find_all(['th','td'])    # finding out th and td at the same time
  rowlist =[]
  for item in row_data:
    y = item.text.strip()
    rowlist.append(y)
  alldata.append(rowlist)
print(alldata)

import csv
file = open('nepse.csv','w')
x = csv.writer(file)
x.writerows(alldata)
file.close()

import pandas as pd
df = pd.read_csv('nepse.csv', index_col = 'S.No')
df

#df = df[0:10]

LTP = [float(i.replace(',','')) for i in df['LTP']]
LTP

# sorted_df = df.sort_values(by = "Volume",ascending = False)
# sorted_df

import plotly.express as px
fig = px.bar(df[0:10], x= 'Symbol', y='Volume')
fig.show()

import plotly.express as px
fig = px.histogram(df[0:10], x="Symbol", y="LTP", height = 500)

fig.show()

print(df.columns)

df = df[0:10]
df

import plotly.graph_objects as go    #data comparing
High = [float(i.replace(',','')) for i in df['High']]
Symbol = df['Symbol']
Open = df['Open']
Close = df['Prev. Close']
fig = go.Figure(data=[
    go.Bar(name='Open', x=Symbol, y=Open),
    go.Bar(name='Close', x=Symbol, y=Close)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()

import plotly.graph_objects as go
fig = go.Figure([go.Bar(x=Symbol, y=LTP)])

fig.show()

import plotly.graph_objects as go
import pandas as pd

fig = go.Figure(data=[go.Candlestick(x=df['Symbol'],
              open=df['Open'], high=df['High'],
                low=df['Low'], close=df['Prev. Close'])
                     ])

fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()

#through this we can find open close high and low price of the stock

import matplotlib.pyplot as plt
x = df['Symbol']
y = df['LTP']
plt.plot(x,y)
plt.title('Stock price plot')
plt.xlabel('Symbol')
plt.ylabel('Stock price')

plt.show()

x = df['Symbol']
y1 = df['High']
y2 = df['Low']
plt.plot(x,y1,label = "High")   #defining label
plt.plot(x,y2, label = "Low")
plt.title('Stock price plot')
plt.xlabel('Symbol')
plt.ylabel('Stock price high and low')
plt.legend()     # if you want to add lable types you have to define legend
plt.show()

df['new_Volume'] = [float(i.replace(',','')) for i in df['Volume']]
df['new_Volume']

sorted_df = df.sort_values(by = 'new_Volume',ascending = True)

plt.figure(figsize=(15,5))
x = sorted_df['Symbol']
y = sorted_df['new_Volume']
plt.bar(x,y, color = ['r','b','g','k','m','y','c'])
plt.xlabel('Symbol')
plt.ylabel('Transaction volume ')
plt.title('Transaction volume of different stock company')

#plt.legend()
plt.plot()
plt.show()

